### ISSUE TITLE
Ready to support CUDA 7.0 and cudNN v3?

### ISSUE THREAD

**Issue by droidicus** [pluskid/Mocha.jl#109]
Are you ready to start supporting CUDA 7.0 and cudNN v3? I have used it on my local copy, and it is passing all the tests, with a significant speed improvement on my GPU as well (NVidia GTX 980 Ti). If we are ready, then I can submit a pull request for windows libraries (unfortunately, they change the dll names on the windows platform, so they need to be updated).

Thanks!

**Comment by pluskid** [comment]
@droidicus Yes I hope the updating is smooth. I would be very happy to accept the PR. But I believe CUDA 6.5 will be around for a while. So would it possible to make it backward compatible? Maybe we need to add an environment variable to configure what version of cuDNN should be loaded.

**Comment by droidicus** [comment]
The Libdl.find_library() will search for the first entry in a list, so we can just have the 7.0 dll be the first entry and the 6.5 dll be the second. I will submit the PR today.

**Comment by droidicus** [comment]
Hmm, looks like I forgot to set the CUDA ENV parameter when I did this check before, CUDA 7.0 looks fine, but I am getting a test failure with cudNN 3.
```
-- Testing Convolution(frozen=true) on Mocha.GPUBackend{Float64} filter=(3,4)...
    > Setup
    > Forward
minimum(expected_output - got_output) = -8.548903807081842e-8
maximum(expected_output - got_output) = 1.1822297008023952e-7
ERROR: LoadError: LoadError: test failed: all(-eps .< expected_output - got_output .< eps)
 in expression: all(-eps .< expected_output - got_output .< eps)
 in error at error.jl:21
while loading C:\Users\droidicus\.julia\v0.4\Mocha\test\layers/convolution.jl, in expression starting on line 204
while loading C:\Users\droidicus\.julia\v0.4\Mocha\test\runtests.jl, in expression starting on line 84
```
This might be intentional on NVidia's part, as part of their 2x speedup in the new version. The error is still quite small, but larger than the CPU mode by several orders of magnitude.
```
-- Testing Convolution(frozen=true) on Mocha.CPUBackend{Float64} filter=(3,4)...
    > Setup
    > Forward
minimum(expected_output - got_output) = -5.329070518200751e-15
maximum(expected_output - got_output) = 7.105427357601002e-15
```

**Comment by pluskid** [comment]
@droidicus IMO 1e-7 error is still reasonably acceptable (at least I won't consider it a bug). Floating point arithmetics are not associative. So if you do a series of computation in different order, you might get different results. CPU and GPU computation are quite different because CPU do the computation sequentially, while GPU might do computation in groups, blocks, and accumulate local computation results.

**Comment by droidicus** [comment]
@pluskid looks like this would need to be increased to 1e-5 in order to pass all the tests.

If this is still in the acceptable range then I can submit the PR.

**Comment by pluskid** [comment]
@droidicus yes, that is acceptable.
