### ISSUE TITLE
Issue with `unsafe_convert`

### ISSUE THREAD

**Issue by pluskid** [pluskid/Mocha.jl#113]
@droidicus reported that `Compat.unsafe_convert` is making the test for pooling layer to take much longer to run, and we temporarily revert back to the Julia v0.3 syntax (`convert`). This should be investigated and fixed. See #112

**Comment by droidicus** [comment]
Just added a new Pull Request #116, and I don't think I am the right person to work on these changes for Julia 0.4. I have been plugging away on it for the last few days, and have not gotten anywhere, other than to realize that some of the changes I had already made were incorrect.

Sorry that I can't be of more help on this!

**Comment by pluskid** [comment]
@droidicus Thanks anyway! I agree that the underlying interface is getting a bit complicated and needs some refactoring. I'm holding it to wait Cxx.jl to be more mature and then we could potentially get a much cleaner internal API.

**Comment by droidicus** [comment]
Another option could be to use some of the other JuliaGPU libraries such as:
https://github.com/JuliaGPU/CUDNN.jl
https://github.com/JuliaGPU/CUBLAS.jl
https://github.com/JuliaGPU/CUDA.jl
https://github.com/JuliaGPU/CUDArt.jl
