### ISSUE TITLE
mathematical error in GaussianKLLossLayer

### ISSUE THREAD

**Issue by jeff-regier** [pluskid/Mocha.jl#117]
In `GaussianKLLossLayer`, the KL divergence between the Gaussian distributions `N(mu, sigma)` and `N(0, 1)` appears to be incorrect, both in the code and in the documentation.  For example, the KL divergence should contain the term `log(sigma)` and shouldn't contain the term `log(2pi)`.

https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence#Kullback.E2.80.93Leibler_divergence_for_multivariate_normal_distributions

**Comment by jeff-regier** [comment]
I have a version that's working with a CPUBackend in a fork of Mocha.jl:

https://github.com/jeff-regier/Mocha.jl/blob/master/src/layers/encoder-loss.jl

You may wish to copy the relevant parts. I also a have unit test for `forward` that verifies the KL divergence by monte carlo simulation, and a unit test for `backward` that verifies the derivatives by finite differences.

https://github.com/jeff-regier/Mocha.jl/blob/master/test/layers/encoder-loss.jl

These unit tests depend on `GSL.jl` and `Distributions.jl`, so I presume you wouldn't want to include these unit tests in `Mocha.jl`.

**Comment by benmoran** [comment]
That is embarrassing but thank you!  I'll fix it.

**Comment by jeff-regier** [comment]
Oh it's really easy to get kl divergence slightly off... happens to me often. Thanks for fixing it!
