### ISSUE TITLE
AbstractFloat not defined

### ISSUE THREAD

**Issue by tlienart** [pluskid/Mocha.jl#142]
Hello,

I'm trying to use the github version of Mocha (*) with Julia 3.11 (on remote servers so upgrading to 0.4 is not the most convenient option), collaborators of mine seem to have managed to get it to work but for some reason I'm always confronted with 

```
Pkg.clone("https://github.com/pluskid/Mocha.jl.git")
using Mocha
Configuring Mocha...
 * CUDA       disabled by default
 * Native Ext disabled by default
Mocha configured, continue loading module...
ERROR: AbstractFloat not defined
 in include at /usr/bin/../lib64/julia/sys.so
 in include_from_node1 at /usr/bin/../lib64/julia/sys.so
 in include at /usr/bin/../lib64/julia/sys.so
 in include_from_node1 at /usr/bin/../lib64/julia/sys.so
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
while loading .../v0.3/Mocha/src/blob.jl, in expression starting on line 128
while loading .../v0.3/Mocha/src/Mocha.jl, in expression starting on line 28
```

Any help would be greatly appreciated, thanks!

(* I need the git version so that I can use options "suffle=true", and LReLU neurons)

**Comment by pluskid** [comment]
@tlienart It might be that you did not have `Compat.jl` installed, which is used to keep backward compatibility with v0.3. I have updated the git version to require `Compat.jl`. Can you test again? Thanks for reporting this!

**Comment by tlienart** [comment]
Thanks for the quick reply! after removing `~/.julia/v0.3/Mocha` and cloning again, it still didn't work (same error) but the `Compat.jl` is indeed the key, (I did `Pkg.add("Compat")` and now Mocha seems to work)

**Comment by pluskid** [comment]
Great!
