### ISSUE TITLE
Impossible to defstruct a Layer outside Mocha

### ISSUE THREAD

**Issue by lostanlen** [pluskid/Mocha.jl#145]
Macros `@defstruct` and `@characterize_layer` do not work outside the scope of the Mocha package. Therefore, it is unwieldy to define a custom subtype of `Layer` in a separate package.
The documentation gives the following example:
```julia
Mocha.@defstruct MyStruct Any (
          field1 :: Int = 0,
          (field2 :: AbstractString = "", !isempty(field2))
        )
```
but running it in the REPL actually leads to
```
ERROR: syntax: field name "Mocha.field1" is not a symbol.
```
PR #136 did not solve the problem. I believe that other symbols should be escaped (`esc` function) to make this work.
I need this change in order to defstruct a `ScatteringLayer<:Layer` in my research package https://github.com/lostanlen/WaveletScattering.jl.

**Comment by benmoran** [comment]
(copying from my reply to https://github.com/pluskid/Mocha.jl/pull/136)

@lostanlen the example you give seems to work in my version of Mocha, and I've also been able to define layers in other external projects (e.g. https://github.com/benmoran/MochaTheano.jl/blob/master/src/theano-layer.jl)

Are you sure you have the latest Mocha master checked out with Pkg.checkout("Mocha") ?

**Comment by lostanlen** [comment]
Works indeed on latest master after `Pkg.checkout("Mocha")`. Sorry for the trouble. Thanks a lot !

**Comment by pluskid** [comment]
I will try to make a new release as soon as possible. Currently the git version contains quite a lot new things from the community.
