### ISSUE TITLE
Shuffled sequential access in HDF5DataLayer

### ISSUE THREAD

**Issue by jfsantos** [pluskid/Mocha.jl#15]
Currently HDF5DataLayer has a limitation as it is not able to shuffle data if the HDF file is chunked or compressed. In Pylearn2, there is a special mode for accessing data called "shuffled sequential", which basically iterates sequentially over a shuffled version of the dataset. Even though shuffling the a whole chunked/compressed dataset is infeasible, I think we could access chunks in a random order and also shuffle the contents inside each chunk, given that chunks are larger than the batch size (or ideally a multiple of the batch size). Maybe this is too specific for adding to the library, so I wanted to ask if such a thing would be interesting in general before I start working on it.

**Comment by pluskid** [comment]
@jfsantos Thanks again for suggesting this. I'm closing this issue since this is now completely implemented in the new `AsyncHDF5DataLayer` as in v0.0.7. It supports both async data reading (with noticeable speed improvement for my own experiments) and chunked shuffling.
