### ISSUE TITLE
back-propagation for softmax layer

### ISSUE THREAD

**Issue by jeff-regier** [pluskid/Mocha.jl#160]
Does `SoftmaxLayer` not support back-propagation because you haven't needed that functionality yet, perhaps because softmax is usually followed by a logistic loss, and you can use `SoftmaxLossLayer` instead? (Do you mainly use `SoftmaxLayer` to normalized blobs from a data layer?) Or is implementing back-propagation for `SoftmaxLayer` likely to be challenging (or to not scale well) from some reason?  I'll work on it and submit a PR if you don't foresee any problems.

**Comment by pluskid** [comment]
@jeff-regier back propagation for softmax is actually implemented a while ago. Sorry I forgot to update the document. Just updated it! Thanks for reporting!
