### ISSUE TITLE
ImageNet notebook loads wrong file

### ISSUE THREAD

**Issue by NOTtheMessiah** [pluskid/Mocha.jl#163]
just replace
`model/ilsvrc_2012_mean.hdf5`
with `model/ilsvrc12_mean.hdf5` in https://github.com/pluskid/Mocha.jl/blob/master/examples/ijulia/ilsvrc12/imagenet-classifier.ipynb to fix

**Comment by pluskid** [comment]
Thanks a lot! Just fixed it!
