### ISSUE TITLE
gpubackend() error

### ISSUE THREAD

**Issue by vetrianka** [pluskid/Mocha.jl#164]
Hello,

I guess it is a silly question, but when I am trying to initialize GPU backend, it raises an error:

julia> ENV["MOCHA_USE_CUDA"] = "true"
"true"

julia> using Mocha
WARNING: Method definition info(Any...) in module Base at util.jl:334 overwritte
n in module Logging at C:\Users\ALEXEY\.julia\v0.4\Logging\src\Logging.jl:61.
WARNING: Method definition warn(Any...) in module Base at util.jl:364 overwritte
n in module Logging at C:\Users\ALEXEY\.julia\v0.4\Logging\src\Logging.jl:61.
Configuring Mocha...
 * CUDA       enabled [DEV=0] (MOCHA_USE_CUDA environment variable detected)
 * Native Ext disabled by default
Mocha configured, continue loading module...
DefaultBackend = Mocha.GPUBackend

julia> backend = GPUBackend()
Mocha.GPUBackend

julia> init(backend)
ERROR: error compiling init: error compiling create: could not load library ""
The specified module could not be found.

Would you please help me? 
Here are version numbers:
Windows 8.1 64
Julia 0.4.0
Cuda 7.5.18
Cudnn 3.0
Kernels compiled with Visual Studio 12

**Comment by greenflash1357** [comment]
I guess your cuBLAS library is not found. 

Compare `/src/cuda/cublas.jl` line 39:
`const libcublas = Libdl.find_library(["cublas64_70.dll", "cublas64_65.dll", cublas32_70.dll", "cublas32_65.dll"], [""])`

Your CUDA version is 7.5.

You can add "cublas64_75.dll" to the search list.

**Comment by pluskid** [comment]
@greenflash1357 Thanks!
@vetrianka Yes Julia Libdl basically eat all the error messages when loading dynamic libraries, making it very difficult to debug. Can you try @greenflash1357's suggestion and see if it works? Please let us know so that we could add the fix to the current code repo. Thanks!

**Comment by vetrianka** [comment]
Thank you very much for your reply. When I added "cublas64_75.dll" to the search list the error message changed. Now it is:

29-??? 17:23:26:INFO:root:Initializing CuDNN backend...
ERROR: LoadError: error compiling create: could not load library ""
The specified module could not be found.

 in init at C:\Users\ALEXEY\.julia\v0.4\Mocha\src\cuda/backend.jl:166
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
while loading C:\Users\ALEXEY\.julia\v0.4\Mocha\examples\mnist\mnist1.jl, in exp
ression starting on line 6

I supposed that there is the same issue with Cudann dll, but I have proper name in a search list (in cudann.jl) and it seems to be able to find the library when I execute it from the command prompt:

julia> libcudnn = Libdl.find_library(["cudnn64_70.dll", "cudnn64_65.dll", "cudnn32_70.dll", "cudnn32_65.dll"], [""])
"cudnn64_70.dll"

**Comment by vetrianka** [comment]
Thank you very much for your reply. When I added "cublas64_75.dll" to the search list the error message changed. Now it is:

29-??? 17:23:26:INFO:root:Initializing CuDNN backend...
ERROR: LoadError: error compiling create: could not load library ""
The specified module could not be found.

 in init at C:\Users\ALEXEY\.julia\v0.4\Mocha\src\cuda/backend.jl:166
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
while loading C:\Users\ALEXEY\.julia\v0.4\Mocha\examples\mnist\mnist1.jl, in exp
ression starting on line 6

I supposed that there is the same issue with Cudann dll, but I have proper name in a search list (in cudann.jl) and it seems to be able to find the library when I execute it from the command prompt:

julia> libcudnn = Libdl.find_library(["cudnn64_70.dll", "cudnn64_65.dll", "cudnn32_70.dll", "cudnn32_65.dll"], [""])
"cudnn64_70.dll"

**Comment by vetrianka** [comment]
Thank you very much for your reply. When I added "cublas64_75.dll" to the search list the error message changed. Now it is:

29-??? 17:23:26:INFO:root:Initializing CuDNN backend...
ERROR: LoadError: error compiling create: could not load library ""
The specified module could not be found.

 in init at C:\Users\ALEXEY\.julia\v0.4\Mocha\src\cuda/backend.jl:166
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
while loading C:\Users\ALEXEY\.julia\v0.4\Mocha\examples\mnist\mnist1.jl, in exp
ression starting on line 6

I supposed that there is the same issue with Cudann dll, but I have proper name in a search list (in cudann.jl) and it seems to be able to find the library when I execute it from the command prompt:

julia> libcudnn = Libdl.find_library(["cudnn64_70.dll", "cudnn64_65.dll", "cudnn32_70.dll", "cudnn32_65.dll"], [""])
"cudnn64_70.dll"
