### ISSUE TITLE
julia process interaction with gpu backend

### ISSUE THREAD

**Issue by gdkrmr** [pluskid/Mocha.jl#166]
I have the following Issue using the GPU backend:

I am trying the ```denoising-autoencoder.jl``` example (I changed two lines to make it use the gpu backend) and it seems to work fine. But when I lock my screen, and get back, the julia process will keep consuming 100% cpu without producing any output and the gpu is idle.

I am on a laptop with a nvidia 840m and ubuntu 14.04. I did a quick test with Theano and it seemed to work fine, that is why I am posting here. 

There are some unresolved issues with the power management and the gpu which probably break some internals and cause my computer to freeze sometimes.

I am posting here, because Theano seems to work fine. If the problem is really the linux/nvidia driver interaction, it would be nice to get an error at least.

**Comment by pluskid** [comment]
@gdkrmr Thanks for reporting this. Unfortunately, I have no clue of what is going on here. Does locking the screen also involve potentially putting the computer into sleep? Maybe you could try to ctrl C the julia process and see if it produce any meaningful stack traces.

**Comment by gdkrmr** [comment]
no, the computer does not go to sleep, the screens get turned off though.

When I interrupted the process later with ctrl-c I was in some cublas 
call, but I am not sure if this was just by coincidence. Because of that 
issue I finally changed the setup of my graphic cards and now I can lock 
the screen without problems. I use ```bumblebee``` now and run my script 
with ```optirun julia myscript.jl```. In general I used to have a lot of 
problems with my computer freezing because of the power management of 
the nvidia card but since I got ```bumblebee``` to work the nvidia card 
is only used when it is needed.

There is one thing that I observed: When I start a process with 
```optirun``` and finish it later the gpu does not get turned off until 
I lock my screen.

I doubt that you can fix the problem at ```Mocha```-level, but some 
error would help.

**Comment by pluskid** [comment]
Closing for now as it seems not possible to fix from our side.
