### ISSUE TITLE
unable to init gpu back end. 

### ISSUE THREAD

**Issue by kleinash** [pluskid/Mocha.jl#167]
Kernels build fine. Setting the device works fine: `ENV["MOCHA_USE_CUDA"] = "true"` but `backend = GPUBackend()` throws this error: (is there something I am missing in the install?)

ERROR: LoadError: ccall: could not find function cudnnCreate in library 
 [inlined code] from /home/ashley/.julia/v0.4/Mocha/src/cuda/cudnn.jl:51
 in create at /home/ashley/.julia/v0.4/Mocha/src/cuda/cudnn.jl:62
 in init at /home/ashley/.julia/v0.4/Mocha/src/cuda/backend.jl:166
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/ashley/.julia/v0.4/Mocha/test/runtests.jl, in expression starting on line 18
===============================================================================================================[ ERROR: Mocha ]================================================================================================================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/ashley/.julia/v0.4/Mocha/test/runtests.jl`, ProcessExited(1)) [1]

===============================================================================================================================================================================================================================================
ERROR: Mocha had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71

**Comment by kleinash** [comment]
Thanks to issue #164 I was able to find my issue. I had to change the const link to libcudnn in the cudnn.jl script. Its now a hard link specific to my machine - but at least it works.

**Comment by freddycct** [comment]
cudnn.jl did not update to cuda 7.5 but cublas.jl did...
```
@windows? (
begin
  const libcudnn = Libdl.find_library(["cudnn64_70.dll", "cudnn64_65.dll", "cudnn32_70.dll", "cudnn32_65.dll"], [""])
end
```
