### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by kleinash** [pluskid/Mocha.jl#168]
Haven't a clue what this means: 
```julia
while loading /home/ashley/.julia/v0.4/Mocha/test/layers/softmax.jl, in expression starting on line
ERROR: LoadError: LoadError: test failed: all(-eps .< vec(got_grad) - vec(grad) .< eps)
 in expression: all(-eps .< vec(got_grad) - vec(grad) .< eps)
```

**Comment by pluskid** [comment]
Hi can you provide more information? There should be context information being printed. Something like which layer (softmax here) is being tested on what backend with float32 or float64.

**Comment by kleinash** [comment]
Sorry for the delay in reply. The tests work fine with CPU but not when the running on GPU. Soon as I figure out how to pipe the whole output to file I will post it, for now this is just copy and paste:
```
> using Mocha
> ENV["MOCHA_USE_CUDA"] = "true"
> Pkg.test("Mocha") 
```
Part of the output is in the attached txt file. 
[output.txt](https://github.com/pluskid/Mocha.jl/files/56548/output.txt)
