### ISSUE TITLE
Loading CuModule at non-ASCII path

### ISSUE THREAD

**Issue by greenflash1357** [pluskid/Mocha.jl#169]
I was trying to run the mnist example with GPU-backend.
An error occured at the initialization of the CUDA module, because my home directory contains non-ASCII characters.
```
include("mnist.jl")
04-Dez 22:38:35:INFO:root:Initializing CuDNN backend...
ERROR: LoadError: File not found
 in call at C:\Users\René\.julia\v0.4\Mocha\src\cuda/cuda.jl:89
 in call at C:\Users\René\.julia\v0.4\Mocha\src\cuda/backend.jl:37
 in init at C:\Users\René\.julia\v0.4\Mocha\src\cuda/backend.jl:167
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
while loading C:\Users\René\.julia\v0.4\Mocha\examples\mnist\mnist.jl, in expression starting on line 14
```

Any Ideas how to solve this?

**Comment by pluskid** [comment]
I think this is due to the internal CUDA not supporting unicode in the path of ptx file to load. Unfortunately, I don't think it is possible to solve this from Mocha side.
