### ISSUE TITLE
handling missing values

### ISSUE THREAD

**Issue by gdkrmr** [pluskid/Mocha.jl#170]
I am trying to implement an auto-encoder that can handle missing values in data, is there an easy way to handle missing values in Mocha (e.g. with a quick wrapper around an existing layer) or is it necessary to write a new layer from scratch?

**Comment by pluskid** [comment]
Depending on how you want to handle missing values. If it is OK to set them to a default value (0 or mean, etc.), then it should be fairly easy by wrapping existing layer and do pre-processing before actual computation. However, if you want very specific behavior like ignoring computation for missing values, it will be complicated. For example, the fully connected layers use BLAS to do matrix multiplication, and I do not believe they have any specific interface to handle missing values like that. You will need to write your own computation routine from scratch.
