### ISSUE TITLE
add_tensor4d throws error

### ISSUE THREAD

**Issue by Sasikanth3** [pluskid/Mocha.jl#171]
include("cifar10.jl")
WARNING: Method definition info(Any...) in module Base at util.jl:334 overwritten in module Logging at C:\Users\sragh\.julia\v0.4\Logging\src\Logging.jl:61.
WARNING: Method definition warn(Any...) in module Base at util.jl:364 overwritten in module Logging at C:\Users\sragh\.julia\v0.4\Logging\src\Logging.jl:61.
Configuring Mocha...
 * CUDA       enabled [DEV=0] (MOCHA_USE_CUDA environment variable detected)
 * Native Ext disabled by default
Mocha configured, continue loading module...
DefaultBackend = Mocha.GPUBackend
02-Jan 22:24:06:INFO:root:Initializing CuDNN backend...
02-Jan 22:24:08:INFO:root:CuDNN backend initialized!
02-Jan 22:24:09:INFO:root:Constructing net CIFAR10-train on Mocha.GPUBackend...
02-Jan 22:24:09:INFO:root:Topological sorting 11 layers...
02-Jan 22:24:09:INFO:root:Setup layers...
02-Jan 22:24:13:INFO:root:Network constructed!
02-Jan 22:24:13:INFO:root:Constructing net CIFAR10-test on Mocha.GPUBackend...
02-Jan 22:24:13:INFO:root:Topological sorting 11 layers...
02-Jan 22:24:13:INFO:root:Setup layers...
02-Jan 22:24:13:DEBUG:root:ConvolutionLayer(conv1): sharing filters and bias
02-Jan 22:24:13:DEBUG:root:ConvolutionLayer(conv2): sharing filters and bias
02-Jan 22:24:13:DEBUG:root:ConvolutionLayer(conv3): sharing filters and bias
02-Jan 22:24:13:DEBUG:root:InnerProductLayer(ip1): sharing weights and bias
02-Jan 22:24:14:INFO:root:Network constructed!
02-Jan 22:24:16:DEBUG:root:#DEBUG Checking network topology for back-propagation
02-Jan 22:24:16:DEBUG:root:Init network CIFAR10-train
02-Jan 22:24:16:DEBUG:root:Init parameter filter for layer conv1
02-Jan 22:24:16:DEBUG:root:Init parameter bias for layer conv1
02-Jan 22:24:16:DEBUG:root:Init parameter filter for layer conv2
02-Jan 22:24:16:DEBUG:root:Init parameter bias for layer conv2
02-Jan 22:24:16:DEBUG:root:Init parameter filter for layer conv3
02-Jan 22:24:16:DEBUG:root:Init parameter bias for layer conv3
02-Jan 22:24:16:DEBUG:root:Init parameter weight for layer ip1
02-Jan 22:24:16:DEBUG:root:Init parameter bias for layer ip1
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at deprecated.jl:73
 [inlined code] from deprecated.jl:418
 in unsafe_convert at no file:0
 [inlined code] from C:\Users\sragh\.julia\v0.4\Mocha\src\cuda/cudnn.jl:51
 in convolution_forward at C:\Users\sragh\.julia\v0.4\Mocha\src\cuda/cudnn.jl:323
 in forward at C:\Users\sragh\.julia\v0.4\Mocha\src\cuda\layers/convolution.jl:83
 in forward at C:\Users\sragh\.julia\v0.4\Mocha\src\net.jl:148
 in init_solve at C:\Users\sragh\.julia\v0.4\Mocha\src\solvers.jl:189
 in solve at C:\Users\sragh\.julia\v0.4\Mocha\src\solvers.jl:234
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
while loading C:\Users\sragh\.julia\v0.4\Mocha\examples\cifar10\cifar10.jl, in expression starting on line 62
ERROR: LoadError: Not supported
 [inlined code] from C:\Users\sragh\.julia\v0.4\Mocha\src\cuda/cudnn.jl:53
 in add_tensor4d at C:\Users\sragh\.julia\v0.4\Mocha\src\cuda/cudnn.jl:172
 in forward at C:\Users\sragh\.julia\v0.4\Mocha\src\cuda\layers/convolution.jl:89
 in forward at C:\Users\sragh\.julia\v0.4\Mocha\src\net.jl:148
 in init_solve at C:\Users\sragh\.julia\v0.4\Mocha\src\solvers.jl:189
 in solve at C:\Users\sragh\.julia\v0.4\Mocha\src\solvers.jl:234
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
while loading C:\Users\sragh\.julia\v0.4\Mocha\examples\cifar10\cifar10.jl, in expression starting on line 62

@assert CUDNN_ADD_IMAGE <= mode <= CUDNN_ADD_FULL_TENSOR  line throws an error

my configuration : cudnn64_4.dll and cuda 7.5 on windows 10 (could reproduce both on release build and also the bleeding edge)

**Comment by pluskid** [comment]
It seems cudnn v4 introduced some new algorithms that were not presented before. I have not gotten a chance to test cudnn v4 yet. But you could try to comment out that assertion line and see if it works.

**Comment by pluskid** [comment]
This should be fixed now in a recent commit for fixing cuDNN v4 API changing.
