### ISSUE TITLE
ERROR: LoadError: ccall: could not find function cublasCreate_v2 in library

### ISSUE THREAD

**Issue by kleinash** [pluskid/Mocha.jl#172]
Hi,

Pkg.test("Mocha") works. 

But now I want to use my GPU backend; I set ENV["MOCHA_USE_CUDA"] = "true" 

I find the device no issues `* CUDA       enabled [DEV=0] (MOCHA_USE_CUDA environment variable detected)`
But I get the error: ERROR: LoadError: ccall: could not find function cublasCreate_v2 in library from here: Mocha/src/cuda/cublas.jl:50

EDIT: after a couple days of Pkg.update() I now have the error: `ERROR: LoadError: ccall: could not find function cudnnCreate in library`

Should I be linking libraries at runtime? how do I do that using Julia?

Thx

**Comment by kleinash** [comment]
The issue was with my cudnn install - things where not linking at run time so I had to move my libraries around (to the cuda main folders) to allow Mocha to see them.

**Comment by blairn** [comment]
How did you do this? I'm facing the same problems, but I have no idea how to go about fixing it.

Which files need to be moved, and where do you move them to?

**Comment by kleinash** [comment]
I moved to MXNet.

**Comment by davidparks21** [comment]
What version of the cuda libraries were you using, I use Cuda 7.5 libraries with CUDNN libraries v4. Also, some troubleshooting steps in this issue might be helpful to you: https://github.com/pluskid/Mocha.jl/issues/199

**Comment by cswwp** [comment]
I use Cuda 7.5 libraries with CUDNN libraries v4, also i face this problem, and how do you fix it?

**Comment by davidparks21** [comment]
Check that the correct versions of cuda/cudnn are listed first in LD_LIBRARY_PATH. You might also search the code for LD_LIBRARY_PATH and see what it's searching for and verify on your system that it's there. I dealt with some similar issues when I got it working, however nowadays I'm using tensorflow, so I can't offer much more specific advice.
