### ISSUE TITLE
test.txt file 

### ISSUE THREAD

**Issue by kleinash** [pluskid/Mocha.jl#177]
Hi,

This is more of a question than an issue. I have a list of hdf5 files, and taking the lead from the tutorial I list them in my test.txt file - but when I run the training I think its only seeing the one file rather than looping through all of them (and concatenating them somehow) 

Should I be doing this outside of the txt file? Because putting together a 4d hdf5 file is proving to be tough. 

Thx

EDIT: also a really basic question - but how do I access the obj_val at each iteration? to work out the RMSE.. Or is there an easier way to find the training error?

**Comment by pluskid** [comment]
It is supposed to be iterating through all files as shown [here](https://github.com/pluskid/Mocha.jl/blob/master/src/layers/async-hdf5-data.jl#L83). If it is not working, there must be something wrong somewhere. Could you make a minimum example that could reproduce the bug?

**Comment by kleinash** [comment]
Hi,

I guess the minumim example would be your mnist tutorial. I pretty much used that as my base. 

```julia
data_layer  = HDF5DataLayer(name="train-data", source="data/train.txt",
    batch_size=64, shuffle=true)
``` etc... 

Only my train.txt lists:
```txt
/input_data/train1.h5
/input_data/train2.h5
/input_data/train3.h5
/input_data/train4.h5
```txt

(with full paths)

When you do your training yours says:  Accuracy (avg over 10000) = X.0000%
Which is your full database

but when I do my training:  Accuracy (avg over 200) = 39.0000%
200 is the value of data lines in each of my h5 files - so I was expecting to see 1000

BUT now that I look closer - I only have 200 in my testing data, so obviously its only going to say 200.. I think.. 

NOW that I have your attention - which I really really appreciate - I was wondering if you could help me with how to find the training error easily? Is there a method that I am missing? 

I get the value for each predicted y - and I could load each of my h5 files to find the actual value. But I am guessing you have already gone to all this trouble there has to be a way already set up that spits out the training error.. 
And if I wanted to plot the training error against the test error - how do I access the values that are being printed by solver(solver,net) and the coffee breaks? 

Thank you for all your time..

**Comment by pluskid** [comment]
If you set up a "coffee lounge" (see [the doc here](http://mochajl.readthedocs.org/en/latest/user-guide/solver.html#solver-coffee-breaks)), the statistics will be saved automatically. You can load them later (see for example `tools/plot_statistics.jl`).

**Comment by kleinash** [comment]
Thank you! knew I was missing something - will check it out and come close this if its all sorted.
