### ISSUE TITLE
how to use method dump_statistics 

### ISSUE THREAD

**Issue by kleinash** [pluskid/Mocha.jl#178]
Hi,

I get an error when running ```update_statistics(solver,:obj_value, :obj_val)```

LoadError: MethodError: `update_statistics` has no method matching update_statistics(::Mocha.Solver{Mocha.SGD}, ::Symbol, ::Symbol)
Closest candidates are:
  update_statistics(::Any, !Matched::AbstractString, !Matched::AbstractFloat)
while loading In[19], in expression starting on line 2

The API shows:
***
dump_statistics(storage, layer_state, show)

storage is a data storage (typically a CoffeeLounge object) that is used to dump statistics into, via the function update_statistics(storage, key, value).

show is a boolean value, when true, indicating that a summary of the statistics should also be printed to stdout.
***

How do I use this? 

EDIT: I would like to scatter plot predicted value and actual value over my epoch. Is there a way to access these two things? I updated today and see now there are 3 options for plot_statistics.jl rather than 4.

**Comment by kleinash** [comment]
Looks like I have to move over to MXNet and start again..

**Comment by pluskid** [comment]
The statistics is usually not used to save values like predictions. To save the predictions, you can use a memory-output or hdf5-output layer to capture the predictions, and then inspect them later.

**Comment by kleinash** [comment]
Aaaah thank you. Is this the same for MXNet.jl? 
Moving over there as directed.

**Comment by pluskid** [comment]
No MXNet.jl is simpler for doing this. See the end of the README at the home page of MXNet.jl (https://github.com/dmlc/MXNet.jl).
