### ISSUE TITLE
ERROR: Blosc 

### ISSUE THREAD

**Issue by xiaojidan** [pluskid/Mocha.jl#194]
I install Mocha on ubuntu 14.04, but it fails. It shows "LoadError: failed process: Process(`curl -f -o c-blosc-1.7.0.tar.gz -L https://github.com/Blosc/c-blosc/archive/v1.7.0.tar.gz`, ProcessExited(77)) [77]
while loading /home/qw/.julia/v0.4/Blosc/deps/build.jl, in expression starting on line 18
"
"================================[ BUILD ERRORS ]================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in /home/qw/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

"
Can you solve it? I have this problem on different ubuntu 14.04, I check it, but it fails. Can you help me solve it ?
Thank you very much.

**Comment by pluskid** [comment]
This error is from building the Blosc.jl package. I would suggest asking at Blosc.jl or HDF5.jl 's issue list.

**Comment by xiaojidan** [comment]
OK. Thanks a lot. @pluskid
