### ISSUE TITLE
CUDA 7.5 GPU backend test fail

### ISSUE THREAD

**Issue by davorh** [pluskid/Mocha.jl#203]
test fails with GPU backed. CPU backend works fine, latest github version is installed.
Full output attached, error snip:

-- Testing convolution layer with shared param on Mocha.GPUBackend{Float64}...
30-May 10:35:01:INFO:root:Constructing net test-shared-params on Mocha.GPUBackend...
30-May 10:35:01:INFO:root:Topological sorting 5 layers...
30-May 10:35:01:INFO:root:Setup layers...
ERROR: LoadError: LoadError: Bad param
 [inlined code] from /home/sageusr/.julia/v0.4/Mocha/src/cuda/cudnn.jl:53
 in get_convolution_forward_algorithm at /home/sageusr/.julia/v0.4/Mocha/src/cuda/cudnn.jl:286
 in setup_etc at /home/sageusr/.julia/v0.4/Mocha/src/cuda/layers/convolution.jl:38
 in call at /home/sageusr/.julia/v0.4/Mocha/src/layers/convolution.jl:120
 in setup at /home/sageusr/.julia/v0.4/Mocha/src/layers/convolution.jl:158
 in call at /home/sageusr/.julia/v0.4/Mocha/src/net.jl:227
 in test_shared_parameters_layers at /home/sageusr/.julia/v0.4/Mocha/test/layers/shared-parameters.jl:25
 in test_shared_parameters_layers at /home/sageusr/.julia/v0.4/Mocha/test/layers/shared-parameters.jl:42
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in anonymous at /home/sageusr/.julia/v0.4/Mocha/test/runtests.jl:26
 in map_to! at abstractarray.jl:1286
 in map_to! at abstractarray.jl:1295
 in map at abstractarray.jl:1308
 in test_dir at /home/sageusr/.julia/v0.4/Mocha/test/runtests.jl:25
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/sageusr/.julia/v0.4/Mocha/test/layers/shared-parameters.jl, in expression starting on line 50
while loading /home/sageusr/.julia/v0.4/Mocha/test/runtests.jl, in expression starting on line 85
================================[ ERROR: Mocha ]================================

failed process: Process(`/opt/julia/usr/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/sageusr/.julia/v0.4/Mocha/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================

[Mocha-test.zip](https://github.com/pluskid/Mocha.jl/files/289215/Mocha-test.zip)

**Comment by davidparks21** [comment]
Are you using CuDNN (Cuda Neural Network library) version 5? If so, downgrade that to v4 and you should be good to go. The issue with CuDNN v5 is already open in a couple of places (which should probably be consolidated), here's one I posted: https://github.com/pluskid/Mocha.jl/issues/198

Also take a look at this related issue, if Mocha doesn't find the CuDNN v4 library you might need to checkout the latest master from the repo, or just manually apply the simple fix I referenced there.

https://github.com/pluskid/Mocha.jl/issues/199

**Comment by davorh** [comment]
Yes, version 5. Tnx I'll use #199 :)
