### ISSUE TITLE
How can I implement a network with multiple datalayers in Mocha?

### ISSUE THREAD

**Issue by AStupidBear** [pluskid/Mocha.jl#204]
Here is a toy model of my project. Since there's no such a kind of examples in Mocha, I don't know how to deal with the input data.
![net](https://cloud.githubusercontent.com/assets/16422976/15714685/12ac586c-284e-11e6-9a15-2119c017d426.jpg)

**Comment by greenflash1357** [comment]
You can easily reuse the same data layer as bottom for two different layers.
Simply put `bottoms=[:data]` in the definitions of your d1 and d2 layers.

As introduction to layer construction, have a look at the [MNIST example](http://mochajl.readthedocs.io/en/latest/tutorial/mnist.html), ([source](https://github.com/pluskid/Mocha.jl/blob/master/examples/mnist/mnist.jl)).

**Comment by AStupidBear** [comment]
Thanks for your response. However, in my problem d1 and d1 are different data layers using different data.

**Comment by greenflash1357** [comment]
I see. The updated sketch explains your problem much better.
For final clarification: Do you want `ip1` to be a bottom of `ip2`? Or do you want `ip1` and `ip2` to share parameters?

**Comment by AStupidBear** [comment]
ip1 is a bottom of ip2

**Comment by AStupidBear** [comment]
bottomSent from my Huawei Mobile

**Comment by AStupidBear** [comment]
@greenflash1357 Could Mocha do this?

**Comment by greenflash1357** [comment]
From what I know, Mocha can do this.
Two notable things:

1. Output blob of `ip1` and output blob of `d2` should share feature dimensions. If they do, `ip2` can combine the two bottoms.
2. You might need a [`Split Layer`](http://mochajl.readthedocs.io/en/latest/user-guide/layers/util-layer.html#SplitLayer), so that Mocha can handle the back propagation from `l1` and `l2` to `ip1`.

**Comment by AStupidBear** [comment]
How can I deal with :data? I haven't seen an example that use :data2Sent from my Huawei Mobile

**Comment by greenflash1357** [comment]
Depending on the source of your data, you can either create one [data layer](http://mochajl.readthedocs.io/en/latest/user-guide/layers/data-layer.html) with two [tops](http://mochajl.readthedocs.io/en/latest/user-guide/layers/data-layer.html#HDF5DataLayer.tops) or vice versa.

If you have HDF5 files, the `tops` of the data layer are the names of the HDF5 datasets as `Symbol`s. If you have a `MemoryDataLayer` the tops can be arbitrary symbols.

Please provide us with more detailed information if you have further questions.

**Comment by AStupidBear** [comment]
@greenflash1357 Thank you. I'll try.

**Comment by AStupidBear** [comment]
```julia
function dataProvider()
    x=shuffle([linspace(-5,5,10000);])'
    inputBase=x
    outputBase=1./(1+x.^2)
  return inputBase,outputBase
end 
```

```julia
inputBase,outputBase=dataProvider();
LayerSize = 1000
# create the network
d1 = MemoryDataLayer(batch_size=50, data=Array[inputBase,outputBase],tops=[:data1,:label1])
d2 = MemoryDataLayer(batch_size=50, data=Array[inputBase,outputBase],tops=[:data2,:label2])
ip1 = InnerProductLayer(name="ip1",neuron=Neurons.ReLU(), output_dim=LayerSize, tops=[:ip1], bottoms=[:data1])
ip1_split=SplitLayer(bottoms=[:ip1],tops=[:ip1_ip2,:ip1_o1])
ip2 = InnerProductLayer(name="ip2",neuron=Neurons.ReLU(), output_dim=LayerSize, tops=[:ip2], bottoms=[:ip1_ip2,:data2])
o1 = InnerProductLayer(name="o1", output_dim=1, tops=[:o1], bottoms=[:ip1_o1] )
o2= InnerProductLayer(name="o2", output_dim=1, tops=[:o2], bottoms=[:ip2] )
l1 = SquareLossLayer(name="loss", bottoms=[:o1, :label1])
l2 = SquareLossLayer(name="loss", bottoms=[:o2, :label2])
net = Net("rnn-train", backend, [d1,ip1,ip1_split,o1,l1,d2,ip2,o2,l2])
```

Get the following error:
```julia
julia> ip2 = InnerProductLayer(name="ip2",neuron=Neurons.ReLU(), output_dim=LayerSize, tops=[:ip2], bottoms=[:ip1_ip2,:data2])
ERROR: AssertionError: length(bottoms) == length(tops)
 in __InnerProductLayer#16__ at no file
```

**Comment by greenflash1357** [comment]
Try a [Concat Layer](http://mochajl.readthedocs.io/en/latest/user-guide/layers/util-layer.html#ConcatLayer) to combine the output of `ip1` and `d2`.

**Comment by AStupidBear** [comment]
Sorry, I missed Concat LayerSent from my Huawei Mobile

**Comment by AStupidBear** [comment]
@greenflash1357 It finally works. Thank you!
