### ISSUE TITLE
SolverState has no field specific in get_learning_rate

### ISSUE THREAD

**Issue by Nectarineimp** [pluskid/Mocha.jl#234]
The mnist-demo.jl produces this error upon entering the solver loop:

WARNING: Method definition info(Any...) in module Base at util.jl:324 overwritten in module Logging at /home/peter.mancini/.julia/v0.5/Logging/src/Logging.jl:115.
WARNING: Method definition warn(Any...) in module Base at util.jl:354 overwritten in module Logging at /home/peter.mancini/.julia/v0.5/Logging/src/Logging.jl:115.
ERROR: LoadError: type SolverState has no field specific
 in get_learning_rate(::Mocha.LRPolicy.DecayOnValidation, ::Mocha.SolverState{Mocha.SGDSolverState}) at /home/peter.mancini/.julia/v0.5/Mocha/src/solvers/policies.jl:131
 in update(::Mocha.Solver{Mocha.SGD}, ::Mocha.Net{Mocha.CPUBackend}, ::Mocha.SolverState{Mocha.SGDSolverState}) at /home/peter.mancini/.julia/v0.5/Mocha/src/solvers/sgd.jl:69
 in onestep_solve(::Mocha.Solver{Mocha.SGD}, ::Mocha.Net{Mocha.CPUBackend}, ::Mocha.SolverState{Mocha.SGDSolverState}) at /home/peter.mancini/.julia/v0.5/Mocha/src/solvers.jl:210
 in do_solve_loop(::Mocha.Solver{Mocha.SGD}, ::Mocha.Net{Mocha.CPUBackend}, ::Mocha.SolverState{Mocha.SGDSolverState}) at /home/peter.mancini/.julia/v0.5/Mocha/src/solvers.jl:242
 in solve(::Mocha.Solver{Mocha.SGD}, ::Mocha.Net{Mocha.CPUBackend}) at /home/peter.mancini/.julia/v0.5/Mocha/src/solvers.jl:235
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/peter.mancini/Mocha_demo/mnist/mnist-demo.jl, in expression starting on line 65

I am on CentoOS 6.8, x86_64, dual nVidia Titans, 256GB ram, 4 processors. Julia is 0.5.1

I looked through all the code and I didn't see anything obviously wrong. I can't find a reference to a field named 'specific' either. Odd.

**Comment by pluskid** [comment]
Thanks for reporting. This should be fixed in the latest version. I'm making a new maintenance release soon.
