### ISSUE TITLE
Julia 0.6 and Mocha instalation

### ISSUE THREAD

**Issue by rNMF** [pluskid/Mocha.jl#235]
problem with Pkg.add("Mocha")  in Julia 0.6;
it gives:
LoadError: failed process: Process(`g++ -fPIC -Wall -O3 -shared '' -o libmochaext.so im2col.cpp pooling.cpp`, ProcessExited(1)) [1]

**Comment by greenflash1357** [comment]
Most likely you are running under Windows. 
As the [documentation](http://mochajl.readthedocs.io/en/latest/user-guide/backend.html#cpu-backend-with-native-extension) states the native extension can currently not be compiled under windows.

You can safely ignore the error during the automatic build of Mocha.
