### ISSUE TITLE
examples/mnist/convert.jl needs to be updated to work on Julia 0.6

### ISSUE THREAD

**Issue by Chunkulator** [pluskid/Mocha.jl#240]
The readbytes() function used in examples/mnist/convert.jl seems to no longer be defined in Julia 0.6. Presumably it's from an earlier version of Julia.

Changing the two invocations of readbytes() to read(f, UInt8, count) fixes it:
      line 43: img = read(data_f, UInt8, batch_size * h*w)
      line 45: class = read(label_f, UInt8, batch_size)

**Comment by greenflash1357** [comment]
This issue is handled in #238

**Comment by pluskid** [comment]
The fix has been incorporated in a new release now.
