### ISSUE TITLE
Exports of undefined variables

### ISSUE THREAD

**Issue by djsegal** [pluskid/Mocha.jl#244]
I get the following variables as undefined:
+ `get_param_key`
+ `show_statistics`
+ `SGDSolverParameters`

----

This lead me to wonder what the following lines do:

+ https://github.com/pluskid/Mocha.jl/blob/611505d89a69102e0f4d2a870007f4d8540a8028/src/layers.jl#L17
+ https://github.com/pluskid/Mocha.jl/blob/611505d89a69102e0f4d2a870007f4d8540a8028/src/layers.jl#L18
+ https://github.com/pluskid/Mocha.jl/blob/d4a1774c389b5a47a383c24d2737c7c3eb620099/src/solvers/sgd-common.jl#L3

**Comment by pluskid** [comment]
Thanks for pointing this out! Those are legacy functions that we forgot to remove. I have fixed them now.
