### ISSUE TITLE
imageNet classifier example is still using the type Image from Images.jl

### ISSUE THREAD

**Issue by einzigsue** [pluskid/Mocha.jl#245]
The type Image is not available any more in the Image.jl module. Can the function definition in image-classifier.jl be updated?

Cheers
Yue

**Comment by pluskid** [comment]
@einzigsue Thanks for pointing out. Would you like to make a patch for that?

**Comment by einzigsue** [comment]
Hi Chiyuan，

I briefly tried last night but my fix doesn’t work yet. I tried to replace the type Image with current type ImageMeta but the simple replacement does not work well. I guess I need to look up how ImageMeta differs from the deprecated Image type before I make any further patch. Do you have any suggestions? 

Which version of Images.jl was the example using? I just start to look into Julia so fairly new to all the packages but if I know the version I can lookup the document figure out the difference.

Cheers
Yue

**Comment by pluskid** [comment]
I haven't been following the latest development of ImageMeta for a while. Basically what the original code does is to load an imagefile from the disk and extract the content as a standard Julia Array with numerical values representing the RGB pixel values.

Something that might need careful treatment is weather the image is oriented WxH or HxW, and how the channels are ordered (RGB or BGR), etc.

**Comment by blue0rabbit** [comment]
Any ideas what can I use instead Image type? Thanks for all sugestions

**Comment by greenflash1357** [comment]
#248 handles the issue by replacing `Image`with `AbstractArray`. It uses `FileIO.jl` to read the images (according to `Image.jl`).
However, I personally would prefer to handle the IO with `PyPlot.jl` and directly treat images as `Array{Float}`.
