### ISSUE TITLE
could not load module libcuda: dlopen(libcuda.dylib, 1): image not found

### ISSUE THREAD

**Issue by arshak** [pluskid/Mocha.jl#3]
I am able to compile and execute all CUDA samples on my machines and successfully built kernels.ptx

but when I try to startup the backend I get the following error:

22-Nov 13:55:25:INFO:root:Initializing CuDNN backend...
error compiling init: could not load module libcuda: dlopen(libcuda.dylib, 1): image not found
while loading In[9], in expression starting on line 2

 in init at /Users/arshakn/.julia/v0.3/Mocha/src/cuda/backend.jl:131
 in init at /Users/arshakn/.julia/v0.3/Mocha/src/system.jl:11

nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Mon_Oct_20_21:28:13_CDT_2014
Cuda compilation tools, release 6.5, V6.5.24

versioninfo(true)

Julia Version 0.3.2

Commit 21d5433\* (2014-10-21 20:18 UTC)

Platform Info:

  System: Darwin (x86_64-apple-darwin13.3.0)

  CPU: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz

  WORD_SIZE: 64

  uname: Darwin 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64 i386

Memory: 16.0 GB (10326.09375 MB free)

Uptime: 394005.0 sec

Load Avg:  2.4765625  1.91796875  1.77685546875

Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz: 

```
   speed         user         nice          sys         idle          irq
```
#1  2400 MHz      86129 s          0 s      76973 s     800226 s          0 s
#2  2400 MHz       6524 s          0 s       3337 s     953296 s          0 s
#3  2400 MHz      57648 s          0 s      33256 s     872255 s          0 s
#4  2400 MHz       5638 s          0 s       2547 s     954971 s          0 s
#5  2400 MHz      48554 s          0 s      26602 s     888002 s          0 s
#6  2400 MHz       5108 s          0 s       2290 s     955757 s          0 s
#7  2400 MHz      41670 s          0 s      22129 s     899358 s          0 s
#8  2400 MHz       4721 s          0 s       2109 s     956325 s          0 s

  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)

  LAPACK: libopenblas

  LIBM: libopenlibm

  LLVM: libLLVM-3.3

Environment:

  GEM_HOME = /Users/arshakn/.rvm/gems/ruby-2.0.0-p247

  TERM = xterm-256color

  D4M_HOME = /Users/arshakn/d4m_api

  MY_RUBY_HOME = /Users/arshakn/.rvm/rubies/ruby-2.0.0-p247

  PATH = /Applications/Julia-0.3.2.app/Contents/Resources/julia/bin:/Applications/Julia-0.3.2.app/Contents/Resources/julia/libexec/git-core:/Users/arshakn/anaconda/bin:/Users/arshakn/google-cloud-sdk/bin:/opt/local/bin:/opt/local/sbin:/Users/arshakn/orca/bin:/opt/local/bin:/usr/local/spark-0.8.0-incubating:/Developer/NVIDIA/CUDA-6.5/bin:/Users/arshakn/.rvm/gems/ruby-2.0.0-p247/bin:/Users/arshakn/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/arshakn/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/arshakn/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Applications/domino:/usr/local/go/bin

  HOME = /Users/arshakn

  DYLD_LIBRARY_PATH = /Developer/NVIDIA/CUDA-6.5/lib:

  GEM_PATH = /Users/arshakn/.rvm/gems/ruby-2.0.0-p247:/Users/arshakn/.rvm/gems/ruby-2.0.0-p247@global

  FONTCONFIG_PATH = /Applications/Julia-0.3.2.app/Contents/Resources/julia/etc/fonts

  GIT_EXEC_PATH = /Applications/Julia-0.3.2.app/Contents/Resources/julia/libexec/git-core

**Comment by michael-p** [comment]
@arshak You need to also add /usr/local/cuda/lib to DYLD_LIBRARY_PATH because that's where libcuda.dylib lives on a Mac.
