### ISSUE TITLE
Data I/O

### ISSUE THREAD

**Issue by stnava** [pluskid/Mocha.jl#37]
hi - i am new to the mocha package but am very intrigued.  i've successfully run several of your examples and read through the documentation and am very impressed w/the work.   now, i am hoping to try some of my own data.   much of my data is stored in the form exemplified here:

https://github.com/ntustison/KapowskiChronicles/blob/master/analytics2/labelresultsANTsOVolume.csv

for this file, we might want to use columns 5 through ncol(data) to predict column 4 ( age ) or column 3 (sex)

what i am hoping is that you could show me how to map this data into a format that could be used with Mocha.  e.g. via HDF5DataLayer ... i have additional data that is in the form of images and usually employ R for learning tasks.   so, ultimately, i would like to be able to do the same with images ... fyi, i have read through the examples/mnist scripts but was hoping that you could help with the case outlined above: i.e. how to take a csv file and use its entries to do train / test w/Mocha. 

thanks again for this work!

**Comment by pluskid** [comment]
@stnava Ultimately, we might add data layers that could read CSV or image files directly. But for now, you will need to convert them into HDF5 files. Basically, as you could see from the conversion script provided in the examples. You will need to read the columns of your CSV files, and store them as matrix in the HDF5 file. Specifically, you will need to create two *datasets* in HDF5, one for data and one for label. I guess label will corresponds to one column in your CSV file. And data will corresponds to some multiple columns. Say you have M columns for data and there are N rows, then you will need to create a "data" dataset in HDF5 file of the shape M-by-N and a "label" dataset of 1-by-N. Then you read the CSV data and put them in the HDF5 file. See also http://mochajl.readthedocs.org/en/latest/user-guide/layers/data-layer.html

**Comment by stnava** [comment]
hi - thanks for the response ... that is more or less what i gleaned from
the examples but thought i might ask if you were planning other ways to
create data layers ( which it sounds like you are ) ... maybe it would be
convenient to create a csv => hdf5 data / label converter function in
julia, as a short term fix.  or maybe to create the hdf5 directly in R.  i
will think about this a bit more - would like to be able to contribute
something to mocha but doubt my julia skills.  thanks for the documentation
link - and great work!!


brian

**Comment by pluskid** [comment]
@stnava   I thought a little bit about creating things like `CSVDataLayer`. But I think it is rather complicated. Unlike HDF5 datasets which are simple tensors, CSV datasets are rather complicated. It could contain strings, category data, or even missing values. Creating a single `CSVDataLayer` that could handle all those cases is too complicated and I think most of the jobs might already been done in dedicated packages like DataFrames.jl. On the other hand, since Julia is a very high level language with a lot of built-in primitives and related packages for handling data, it is actually very easy to write scripts for manipulating existing data and convert them into standard dataset. The script will be dependent on the structures and properties of the dataset.

**Comment by stnava** [comment]
ok - what about something that is more specific:  a dataframe of 3 columns:


ImageName,Label,TrainTest
image1.jpg,009,Train
image2.jpg,018,Train
....
imageK.jpg,053,Test
...
imageN.jpg,009,Test

or something along these lines?   such a thing could be converted
relatively easily (inside of julia/mocha)
to the appropriate hdf format, no?

even an example script of how to do this ( as Mocha expects it ) would be
helpful ...


brian

**Comment by pluskid** [comment]
@stnava See the latest commit to master: [imglist-to-hdf5.jl](https://github.com/pluskid/Mocha.jl/blob/master/tools/examples/imglist-to-hdf5.jl). You will need to install DataFrames.jl to read CSV files and Images.jl to read images.
