### ISSUE TITLE
Tests fail on Julia 0.3.3 

### ISSUE THREAD

**Issue by rened** [pluskid/Mocha.jl#4]
`Pkg.test("Mocha")` succeeds on `0.3.2`, but fails on `0.3.3` with the following error. Tested both with Mocha 0.0.2 as well as current master. Tested on OSX 10.9.

``` jl
julia> VERSION
v"0.3.3"

julia> Pkg.test("Mocha")
INFO: Testing Mocha
26-Nov 15:25:54:INFO:root:Configuring Mocha...
26-Nov 15:25:54:INFO:root: * CUDA       disabled by default
26-Nov 15:25:54:INFO:root: * Native Ext disabled by default
26-Nov 15:25:54:INFO:root:Mocha configured, continue loading module...
-- Testing RawBLAS{Float32} Utilities
ERROR: ccall: could not find function sgemm_ in library libopenblas
 in gemm! at /Users/rene/.julia/v0.3/Mocha/src/utils/blas.jl:10
 in test_raw_blas at /Users/rene/.julia/v0.3/Mocha/test/utils/blas.jl:11
 in test_raw_blas at /Users/rene/.julia/v0.3/Mocha/test/utils/blas.jl:33
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start at /Users/rene/local/julia/usr/lib/julia/sys.dylib
while loading /Users/rene/.julia/v0.3/Mocha/test/utils/blas.jl, in expression starting on line 37
while loading /Users/rene/.julia/v0.3/Mocha/test/runtests.jl, in expression starting on line 27

==================================================[ ERROR: Mocha ]===================================================

failed process: Process(`/Users/rene/local/julia/usr/bin/julia /Users/rene/.julia/v0.3/Mocha/test/runtests.jl`, ProcessExited(1)) [1]

=====================================================================================================================
INFO: No packages to install, update or remove
ERROR: Mocha had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
```

Thanks!

**Comment by chenych11** [comment]
It seems the `Base.blasfunc` is remove from the 0.5 version. And it fail to pass the test (see below). 
I think the `src/compatibility.jl` file is out of date for julia v0.5. To make it work, modify it like this
```julia
using Compat

function blasfunc(name)
    try
        return Base.blasfunc(name)
    catch
        str_name = string(name)
        fnc_symb = eval(:(Base.@blasfunc $strname))
        fnc_name = string(fnc_symb)
        return fnc_name
    end
end 
```
julia> `versioninfo()`
Julia Version 0.5.0-dev+2089
Commit b97efac* (2016-01-12 00:36 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> `Pkg.test("Mocha")`
INFO: Testing Mocha
WARNING: Method definition info(Any...) in module Base at util.jl:338 overwritten in module Logging at /home/cyc/.julia/v0.5/Logging/src/Logging.jl:61.
WARNING: Method definition warn(Any...) in module Base at util.jl:368 overwritten in module Logging at /home/cyc/.julia/v0.5/Logging/src/Logging.jl:61.
Configuring Mocha...
 * CUDA       disabled by default
 * Native Ext disabled by default
Mocha configured, continue loading module...
ERROR: LoadError: LoadError: LoadError: UndefVarError: blasfunc not defined
 [inlined code] from /home/cyc/.julia/v0.5/Mocha/src/utils/blas.jl:9
 in anonymous at no file:0
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in eval at ./boot.jl:265
 [inlined code] from ./sysimg.jl:14
 in require at ./loading.jl:332
 in include at ./boot.jl:262
 in include_from_node1 at ./loading.jl:401
 in process_options at ./client.jl:245
 in _start at ./client.jl:301
while loading /home/cyc/.julia/v0.5/Mocha/src/utils/blas.jl, in expression starting on line 8
while loading /home/cyc/.julia/v0.5/Mocha/src/Mocha.jl, in expression starting on line 15
while loading /home/cyc/.julia/v0.5/Mocha/test/runtests.jl, in expression starting on line 8
================================[ ERROR: Mocha ]================================

failed process: Process(`/opt/julia/0.5-dev/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/cyc/.julia/v0.5/Mocha/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Base.Pkg.PkgError("Mocha had test errors")
 in test at pkg/entry.jl:671
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:47
 in cd at pkg/dir.jl:31
 in test at pkg.jl:228
 in eval at ./boot.jl:265

**Comment by pluskid** [comment]
@chenych11 Thanks for reporting this! I have incorporated your fix. Could you test if the latest code works on your side? Thanks!

**Comment by lostanlen** [comment]
Thank you for the fix @chenych11. My Travis CI still relies on Mocha v0.1.0, thus fails on the 0.5.0-dev Julia branch. Could you please make a bugfix release v0.1.1. with this change ?

**Comment by pluskid** [comment]
@lostanlen  JuliaLang/METADATA.jl#4684

**Comment by lostanlen** [comment]
:+1:
