### ISSUE TITLE
Channelpoolinglayer description

### ISSUE THREAD

**Issue by rened** [pluskid/Mocha.jl#40]
I am just going through the docs, and this part is perhaps already outdated as the ND-tensors are already implemented?

> This is called channel pooling layer because it is designed to pool over the channel dimension when Mocha can only handle 4D tensors. For general ND-tensors, the “channel” dimension no longer has a specific semantic, and could be specified by the user.

I find "can only handle 4D" confusing - it can do ND now, can't it?
Thanks!

**Comment by rened** [comment]
ah, got it, will post a PR with a re-phase suggestion.

**Comment by pluskid** [comment]
@rened Cool! I agree the current wording is rather confusing.
