### ISSUE TITLE
could not find function cudnnSetFilter4dDescriptor 

### ISSUE THREAD

**Issue by ghalghaz** [pluskid/Mocha.jl#44]
Hello, 

I tried to run mnist.jl.

I got the following message:
20- 1月 20:37:16:INFO:root:Configuring Mocha...
20- 1月 20:37:16:INFO:root: * CUDA       enabled (MOCHA_USE_CUDA environment variable detected)
20- 1月 20:37:16:INFO:root: * Native Ext disabled by default
20- 1月 20:37:16:INFO:root:Mocha configured, continue loading module...
20- 1月 20:37:19:INFO:root:Initializing CuDNN backend...
20- 1月 20:37:19:INFO:root:CuDNN backend initialized!
20- 1月 20:37:20:INFO:root:Constructing net MNIST-train on GPUBackend...
20- 1月 20:37:20:INFO:root:Topological sorting 8 layers...
20- 1月 20:37:20:INFO:root:Setup layers...
ERROR: ccall: could not find function cudnnSetFilter4dDescriptor in library libcudnn
 in set_filter_descriptor at /home/rudy/.julia/v0.3/Mocha/src/cuda/cudnn.jl:41
while loading /home/rudy/.julia/v0.3/Mocha/examples/mnist/mnist.jl, in expression starting on line 22

many thanks for helping

**Comment by pluskid** [comment]
@rudychip What is the version of Mocha and what is the version of cuDNN are you using? The latest version of Mocha requires cuDNN 6.5 R2 which is **not** compatible with R1.

**Comment by rudychip** [comment]
oh I missed reading the CUDA backend's doc. I am using the newest version of Mocha and cuDNN R1.

using cuDNN R2, succeed.

thanks.
