### ISSUE TITLE
Memory data layer

### ISSUE THREAD

**Issue by iceblue25** [pluskid/Mocha.jl#54]
Hi Chiyuan, thanks for the great work. I have read the documentation and tried the tutorial example and works fine. However, I am not able to use Mocha with my own data. I cant figure out how to use save my data in the hdf5 format for non image data. I only need need to use Memory data layer. Can some post a simple example how to feed my data to the Memory Layer? Say I am using an array X_train which is NxM dimensions where N is the number of samples and M is the number of features. Also I have a Y_train Nx1 array which holds the labels for the N samples. How can I feed my data to the Memory Layer? Does any tutorial exist? I cant figure it out from the documentation.

Thanks

**Comment by pluskid** [comment]
Yes, there is a very basic example for `MemoryDataLayer`. See examples/test.jl and also see the (very brief) document of the Memory data layers http://mochajl.readthedocs.org/en/latest/user-guide/layers/data-layer.html#MemoryDataLayer . Basically you define `tops`, which are blob names (defaults to `[:data, :label]`) and you supply the corresponding data array as the `data` field when defining the layer in that order.

**Comment by pluskid** [comment]
@iceblue25 There is a caveat that I think you should transpose your `X_train` so that each **column** is a data sample. Basically your data could be any dimensional tensor, but always the **last** dimension corresponds to the number of samples.
