### ISSUE TITLE
parsing caffemodel

### ISSUE THREAD

**Issue by sunilrao43** [pluskid/Mocha.jl#55]
@pluskid  can you suggest me a way to parse caffemodel to C code

**Comment by sunilrao43** [comment]
@pluskid or could you sugggest me to parse the imported hdf5 file which one might be easier

**Comment by pluskid** [comment]
I'm not sure I understand what you mean. Could you give more details on what do you want to do?

**Comment by sunilrao43** [comment]
I need to parse model trained for alexnet to my C code . Could you help me with a code 
As mocha has done importing the caffemodel to hdf5 so you would be the right person 
to suggest me thanks in advance @pluskid

**Comment by pluskid** [comment]
What I do is very simple: I inject some code to Caffe, so that I could access the caffe model in memory, which are just chunk of memory. I then export to whatever format I like.

**Comment by sunilrao43** [comment]
@pluskid  Thanks for the reply could you help me with a C code

**Comment by sunilrao43** [comment]
@pluskid  if possible you could just suggest me how can start parsing in my C code

**Comment by pluskid** [comment]
Please see https://github.com/pluskid/Mocha.jl/blob/master/tools/dump_network_hdf5.cpp

**Comment by sunilrao43** [comment]
@pluskid  what format would be  correct for me to read in C  thanks in advance

**Comment by pluskid** [comment]
Sorry I do not have a recommendation. It really depends on your own needs and convenience. Typically HDF5 is a very widely used data format that can be easily manipulated in julia, python, matlab, etc. But if you only need to use the it in your C program, you can use / invent any format.
