### ISSUE TITLE
CuDNN Arch mismatch

### ISSUE THREAD

**Issue by bisraelsen** [pluskid/Mocha.jl#57]
Hi,

I'm not sure if this is my problem or not but I am not sure where to go from here. I am getting the following error when trying to initialize the GPU backend.

```
julia>backend = GPUBackend()
GPUBackend
julia>init(backend)
16-Mar 23:11:13:INFO:root:Initializing CuDNN backend...
ERROR: Arch mismatch
 in create at /home/b/.julia/v0.3/Mocha/src/cuda/cudnn.jl:43
 in init at /home/b/.julia/v0.3/Mocha/src/cuda/backend.jl:139
```

I've searched around for "Arch mismatch" online and can't find anything. Any guidance would be great. Thanks!

**Comment by pluskid** [comment]
Hi,

Quoting from cuDNN user guide, `arch mismatch` means

> The function requires a feature absent from the current GPU device. Note that cuDNN only supports devices with compute capabilities greater than or equal to 3.0.
> To correct: compile and run the application on a device with appropriate compute capability.

**Comment by bisraelsen** [comment]
Sorry for the silly question, and thanks for the help!

**Comment by pluskid** [comment]
no problem.
