### ISSUE TITLE
"Invalid Value" when trying to increase batch size with AsyncHDF5DataLayer

### ISSUE THREAD

**Issue by bisraelsen** [pluskid/Mocha.jl#60]
I am using:
```
AsyncHDF5DataLayer(name="train-data", source=train_path, batch_size=100)
```
And get an "Error: Invalid Value" when trying to increase the batch size (say to 150 or 200). Does this have something to do with the chunk_size not being large enough?

Thanks!

**Comment by pluskid** [comment]
@bisraelsen Thanks for reporting this. Do you have a back-trace of where the "Invalid Value" error is raised?

**Comment by bisraelsen** [comment]
```
ERROR: Invalid value
 in launch at /home/brett/.julia/v0.3/Mocha/src/cuda/cuda.jl:79
 in forward at /home/brett/.julia/v0.3/Mocha/src/cuda/neurons.jl:21
 in forward at /home/brett/.julia/v0.3/Mocha/src/net.jl:145
 in solve at /home/brett/.julia/v0.3/Mocha/src/solvers.jl:322
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/brett/GitProjects/NNProj/trainNet.jl, in expression starting on line 156
```

The expression on 156 is : "solve(solver, net)"

**Comment by pluskid** [comment]
The error is thrown from CUDA driver and it occurred when Mocha tries to launch a cuda kernel to compute for the ReLU. I doubt it has anything to do with `AsyncHDF5DataLayer`. Do you mean this error occur when you switched from `HDF5DataLayer` to `AsyncHDF5DataLayer`? Did you upgrade your CUDA driver recently? If you updated CUDA driver, please re-compile the CUDA kernels of Mocha.

**Comment by bisraelsen** [comment]
I am no longer able to create the problem... I am not sure what happened. I was having this problem very repeatably yesterday. I'll keep my eyes peeled and post updates if I get more information.

**Comment by pluskid** [comment]
@bisraelsen I'm closing this issue now. But feel free to re-open if it happens again.
