### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by sgt101** [pluskid/Mocha.jl#65]
Hello, 

I am trying to install Mocha and have hit a brick wall with both the mainline version and the dev version. Here is the error. 

 in hist_from_file at REPL.jl:330
 in setup_interface at REPL.jl:719
 in run_frontend at REPL.jl:837
 in run_repl at REPL.jl:165
 in _start at client.jl:451

INFO: Disabling history file for this session.
julia> Pkg.rm("Mocha")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.clone("https://github.com/pluskid/Mocha.jl.git")
INFO: Cloning Mocha from https://github.com/pluskid/Mocha.jl.git
ERROR: Mocha already exists
 in error at error.jl:21

julia> Pkg.rm("Mocha")
INFO: Removing Mocha (unregistered)

julia> Pkg.clone("https://github.com/pluskid/Mocha.jl.git")
INFO: Cloning Mocha from https://github.com/pluskid/Mocha.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.build("Mocha")
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//rep
odata/repomd.xml
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at deprecated.jl:62
 in unsafe_convert at deprecated.jl:381
 in download at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:49
 in cacheget at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:148
 in update at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:159
 in update at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:126
 in include at boot.jl:252
 in include_from_node1 at loading.jl:133
 in evalfile at loading.jl:175 (repeats 2 times)
 in anonymous at pkg/entry.jl:628
 in cd at file.jl:32
 in build! at pkg/entry.jl:627
 in build! at pkg/entry.jl:622 (repeats 2 times)
 in build at pkg/entry.jl:639
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in build at pkg.jl:64
while loading C:\Users\sgt101\.julia\v0.4\WinRPM\deps\build.jl, in expression starting on line 2
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at deprecated.jl:62
 in unsafe_convert at deprecated.jl:381
 in download at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:49
 in cacheget at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:148
 in update at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:159
 in update at C:\Users\sgt101\.julia\v0.4\WinRPM\src\WinRPM.jl:126
 in include at boot.jl:252
 in include_from_node1 at loading.jl:133
 in evalfile at loading.jl:175 (repeats 2 times)
 in anonymous at pkg/entry.jl:628
 in cd at file.jl:32
 in build! at pkg/entry.jl:627
 in build! at pkg/entry.jl:622 (repeats 2 times)
 in build at pkg/entry.jl:639
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in build at pkg.jl:64
while loading C:\Users\sgt101\.julia\v0.4\WinRPM\deps\build.jl, in expression starting on line 2
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//rep
odata/repomd.xml
INFO: Building Blosc
INFO: Building HDF5
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//rep
odata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//rep
odata/repomd.xml
INFO: Building Mocha
Running `g++ -fPIC -Wall -O3 -shared -fopenmp -o libmochaext.so im2col.cpp pooling.cpp`
==========================================[ ERROR: Mocha ]==========================================

LoadError: could not spawn `g++ -fPIC -Wall -O3 -shared -fopenmp -o libmochaext.so im2col.cpp poolin
g.cpp`: no such file or directory (ENOENT)
while loading C:\Users\sgt101\.julia\v0.4\Mocha\deps\build.jl, in expression starting on line 23

====================================================================================================

==========================================[ BUILD ERRORS ]==========================================

WARNING: Mocha had build errors.

 - packages with build errors remain installed in C:\Users\sgt101\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("Mocha")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================

julia>

**Comment by pluskid** [comment]
Hi, do you have gcc installed? Can you try to execute `g++ -fPIC -Wall -O3 -shared -fopenmp -o libmochaext.so im2col.cpp pooling.cpp` manually or with other compiler other than gcc if you have?

Otherwise you can always use the pure-Julia backend without compiling the native extension.

**Comment by sgt101** [comment]
Ok I did : 

C:\Users\sgt101\.julia\v0.4\Mocha\deps>g++ -fPIC -Wall -O3 -shared -fopenmp -o libmochaext.so im2col
.cpp pooling.cpp
im2col.cpp:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by def
ault]
pooling.cpp:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by de
fault]
g++.exe: error: libgomp.spec: No such file or directory

C:\Users\sgt101\.julia\v0.4\Mocha\deps>

As you can see I am using a windows box....

**Comment by sgt101** [comment]
Also when I try the native code : 

using(mocha)

 

Warning: both Logging and Base export "info"; uses of it in module Mocha must be qualified
Warning: could not import Mocha.info into Config
INFO: Configuring Mocha...
INFO:  * CUDA       disabled by default
INFO:  * Native Ext disabled by default
INFO: Mocha configured, continue loading module...

LoadError: LoadError: LoadError: TypeError: apply_type: in alias, expected Type{T}, got Tuple{DataType,DataType}
while loading C:\Users\sgt101\.julia\v0.4\mocha\src\solvers.jl, in expression starting on line 86
while loading C:\Users\sgt101\.julia\v0.4\mocha\src\mocha.jl, in expression starting on line 75
while loading In[1], in expression starting on line 1

 in include at boot.jl:252
 in include_from_node1 at loading.jl:133
 in include at boot.jl:252
 in include_from_node1 at loading.jl:133
 in reload_path at loading.jl:157
 in _require at loading.jl:69
 in require at loading.jl:52

**Comment by sgt101** [comment]
oh - this closed somehow.. 

I'm still having issues but I've started working on Juliabox now instead

**Comment by pluskid** [comment]
@sgt101 I see that you are using Julia 0.4. Does Julia 0.3 work for you? We try to be compatible with v0.4, but since v0.4 is changing very rapidly, we cannot guarantee that it always runs smoothly.

**Comment by sgt101** [comment]
Hi - I've rolled back to 0.3.9 and it works flawlessly. 

Thanks for your support and assistance; I'm sorry to have taken your time -> I have had a pause in developing for a couple of months and so I was over excited by the availability of 0.4!

**Comment by pluskid** [comment]
The latest updates should work with the **current** v0.4 dev now. But I cannot always guarantee, as v0.4 changes a lot and sometimes it breaks itself.

**Comment by greenflash1357** [comment]
Using Windows 8 and Julia 0.3.11, I have the exact same issue.

**Comment by sgt101** [comment]
Greenflash - can you use 0.3.9 or 4dev? 0.3.9 works for me in win8 and 10 (I can't backward test to 8 now...) I'll try 4dev later this evening to see if that's working now but pluskid says it is so my money is on it being ok :)

**Comment by Ivo-Balbaert** [comment]
I am having the same problem with the standard julia version 0.4.0 on Windows 10
