### ISSUE TITLE
Running test failed

### ISSUE THREAD

**Issue by rouseguy** [pluskid/Mocha.jl#76]
Unable to run Mocha. Running Julia on Mac OSX 10.10.2. When I tried the default test, it failed with the following message

>
julia> Pkg.test("Mocha")
INFO: Testing Mocha
20-Jul 16:17:59:INFO:root:Configuring Mocha...
20-Jul 16:17:59:INFO:root: * CUDA       disabled by default
20-Jul 16:17:59:INFO:root: * Native Ext disabled by default
20-Jul 16:17:59:INFO:root:Mocha configured, continue loading module...
ERROR: JLD not found
 in require at loading.jl:47
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/usrname/.julia/v0.3/Mocha/src/utils/io.jl, in expression starting on line 43
while loading /Users/usrname/.julia/v0.3/Mocha/src/Mocha.jl, in expression starting on line 17
while loading /Users/usrname/.julia/v0.3/Mocha/test/runtests.jl, in expression starting on line 8
>
========================================================[ ERROR: Mocha ]========================================================
>
failed process: Process(`/Applications/Julia-0.3.10.app/Contents/Resources/julia/bin/julia /Users/usrname/.julia/v0.3/Mocha/test/runtests.jl`, ProcessExited(1)) [1]
>
================================================================================================================================
INFO: No packages to install, update or remove
ERROR: Mocha had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67

And tried just this 
`using Mocha`

That gave this error:
>
20-Jul 16:23:10:INFO:root:Configuring Mocha...
20-Jul 16:23:10:INFO:root: * CUDA       disabled by default
20-Jul 16:23:10:INFO:root: * Native Ext disabled by default
20-Jul 16:23:10:INFO:root:Mocha configured, continue loading module...
ERROR: JLD not found
 in require at loading.jl:47
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/usrname/.julia/v0.3/Mocha/src/utils/io.jl, in expression starting on line 43
while loading /Users/usrname/.julia/v0.3/Mocha/src/Mocha.jl, in expression starting on line 17

**Comment by pluskid** [comment]
Hi, Thanks for reporting! It seems that the `JLD` has been separated from `HDF5.jl` and become an independent package. A temporary solution would be explicitly run `Pkg.add("JLD")` in your julia console. I will update the package dependency description soon. Thanks again!

**Comment by pluskid** [comment]
fixed on 59ddccb48ece2575b401807b5f493f9abb26466c
