### ISSUE TITLE
Building from source on a Mac

### ISSUE THREAD

**Issue by vollmersj** [pluskid/Mocha.jl#78]
Building on Linux works perfectly but building on Mac fails. Julia never finishes loading the Mocha:
**Source Code:**
use_gpu = false
if use_gpu
  ENV["MOCHA_USE_CUDA"] = "true"
else
  ENV["MOCHA_USE_NATIVE_EXT"] = "true"
  ENV["OMP_NUM_THREADS"] = 1
  blas_set_num_threads(1)
end
using Mocha
using HDF5
**When killed after 1h:**
^CERROR: interrupt
while loading /Users/sjv/Documents/Mocha2/src/Logging.jl, in expression starting on line 1
while loading /Users/sjv/Documents/Mocha2/src/logging.jl, in expression starting on line 1
while loading /Users/sjv/Documents/Mocha2/src/Mocha.jl, in expression starting on line 4

Anybody any ideas?

**Comment by pluskid** [comment]
@vollmersj Can you try to load either HDF5 or Logging package separately in Julia to see if they load properly? Type this in a julia console, for example
```
using HDF5
```
And also what is the julia version you are using?

**Comment by vollmersj** [comment]
Thank you for your quick response.

I tried this on my laptop and a laptop of a friend with versions 0.3.10 and 0.3.7. The following code block worked without problem

using HDF5
using JLD
using Logging

also just executing the content of Logging.jl in src/ folder of Mocha worked as well:
import Logging
@Logging.configure(level=DEBUG, output=STDOUT)

**Comment by pluskid** [comment]
That's so strange. Could you try to run a `test.jl` with only one line
```
using Mocha
```
in it and paste the full output of running
```
julia test.jl
```
(If it does not finish running in 1 minute, kill it) Thanks!

**Comment by vollmersj** [comment]
If I run julia.jl i don't get any output. From the julia console I get

julia> include("test.jl")
^CERROR: interrupt
while loading /Users/sjv/Documents/Mocha/src/Logging.jl, in expression starting on line 1
while loading /Users/sjv/Documents/Mocha/src/logging.jl, in expression starting on line 1
while loading /Users/sjv/Documents/Mocha/src/Mocha.jl, in expression starting on line 4
while loading /Users/sjv/Documents/Mocha/src/test.jl, in expression starting on line 1

julia>

**Comment by pluskid** [comment]
There should be no problem with Clang compiler I guess, as I'm primarily developing Mocha on OS X. Could you temporarily move `~/.julia/v0.3` to somewhere else, and then re-install Mocha by `Pkg.add("Mocha")` to see if it is because something messed up?

**Comment by pluskid** [comment]
Closing this, please re-open if needed.
